Updated to add proper exit codes, options useful for scripting output

diff --git a/dump_snapshot b/dump_snapshot
--- a/dump_snapshot
+++ b/dump_snapshot
@@ -1,24 +1,50 @@
 #!/bin/bash
 
-SCALEIO_SERVERS="scale1.example.com scale2.example.com scale3.example.com"
+SCALEIO_SERVERS="scaleio1.example.com scaleio2.example.com scaleio3.example.com"
 SCALEIO_PW="SCALEIO_ADMIN_PASSWORD"
 BACKUP_DEVICE=/dev/scinia
 BACKUP_LOCATION=/volumedump
-MYIP=192.168.33.1
-PASSWORD_FILE=/etc/scaleio-backup-password.txt
+MYIP=224.36.61.210
+PASSWORD_FILE=/etc/backup-passwords.txt
 
-display_usage() {
-        echo "This script will attach a given snapshot volume ID, and encrypt it into a gzip file."
-        echo -e "\nUsage:\ndump_snapshot (volume_id)\n"
+show_help() {
+        echo -e "\nThis script will attach a given snapshot volume ID temporarily as ${BACKUP_DEVICE} and encrypt it into a gzip file within ${BACKUP_LOCATION}/."
+        echo -e "\nUsage:  dump_snapshot [OPTIONS] (-i volume_id) \n"
+        echo "OPTIONS:"
+        echo " -h, -?   help"
+        echo " -f       display only the output filepath upon success"
+        echo " -i       scaleIO volume_id to dump"
+        echo -e " -v       increase verbosity\n"
         exit 1
 }
 
-if [  $# -ne 1 ]
+OPTIND=1
+VOLUME_ID=
+FILEPATH_ONLY=0
+VERBOSE=0
+
+while getopts "fh?i:v" opt; do
+    case "$opt" in
+    f)  FILEPATH_ONLY=1
+        ;;
+    h|\?)
+        show_help
+        exit 0
+        ;;
+    i)  VOLUME_ID=$OPTARG
+        ;;
+    v)  VERBOSE=1
+        ;;
+    esac
+done
+
+shift $((OPTIND-1))
+
+if [ "${VOLUME_ID}" == "" ]
 then
-        display_usage
+        show_help
         exit 1
 fi
-VOLUME_ID=$1
 
 #Find out which server is our current primary MDM
 PRIMARY_SERVER=
@@ -34,28 +60,45 @@ for SERVER in ${SCALEIO_SERVERS}; do
 done
 
 if [ "${PRIMARY_SERVER}" != "" ]; then
+  if [ ${VERBOSE} -eq 1 ]; then echo -e "Found primary ScaleIO MDM ${PRIMARY_SERVER}\n"; fi
   OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --query_volume --volume_id ${VOLUME_ID}")
+  if [ ${VERBOSE} -eq 1 ]; then echo -e "${OUTPUT}\n"; fi
   WORKED=$(echo "${OUTPUT}" | grep 'Volume is unmapped')
   if [ $? -eq 0 ]; then
     OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --map_volume_to_sdc --volume_id ${VOLUME_ID} --sdc_ip ${MYIP}")
     #Successfully mapped volume with ID 597033bd0000001f to SDC 224.36.61.124
+    if [ ${VERBOSE} -eq 1 ]; then echo -e "${OUTPUT}\n"; fi
     WORKED=$(echo "${OUTPUT}" | grep 'Successfully mapped')
     if [ $? -eq 0 ]; then
       sleep 5
-      time dd bs=1048576 if=${BACKUP_DEVICE} | gzip -9 --stdout - | openssl enc -e -aes-256-cbc -pass file:${PASSWORD_FILE} -out ${BACKUP_LOCATION}/${VOLUME_ID}.gz
-      ls -lrt ${BACKUP_LOCATION}/${VOLUME_ID}.gz
+      if [ ${FILEPATH_ONLY} -eq 0 ]; then
+         echo "Mapped volume ID ${VOLUME_ID} to ${BACKUP_DEVICE}. Dumping to ${BACKUP_LOCATION}/${VOLUME_ID}.gz"
+         OUTPUT=$(time dd bs=1048576 if=${BACKUP_DEVICE} | gzip -9 --stdout - | openssl enc -e -aes-256-cbc -pass file:${PASSWORD_FILE} -out ${BACKUP_LOCATION}/${VOLUME_ID}.gz)
+      else
+         OUTPUT=$(dd bs=1048576 if=${BACKUP_DEVICE} 2>>/dev/null | gzip -9 --stdout - | openssl enc -e -aes-256-cbc -pass file:${PASSWORD_FILE} -out ${BACKUP_LOCATION}/${VOLUME_ID}.gz)
+      fi
+      if [ $? -eq 0 ]; then
+        if [ ${FILEPATH_ONLY} -eq 0 ]; then
+          echo "${OUTPUT}"; ls -lrt ${BACKUP_LOCATION}/${VOLUME_ID}.gz
+        else 
+          echo "${BACKUP_LOCATION}/${VOLUME_ID}.gz"
+        fi
+      fi
       OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --unmap_volume_from_sdc --volume_id ${VOLUME_ID} --sdc_ip ${MYIP} --i_am_sure")
       #Successfully un-mapped volume with ID 597033bd0000001f from SDC 224.36.61.124
+      if [ ${VERBOSE} -eq 1 ]; then echo -e "${OUTPUT}\n"; fi
       WORKED=$(echo "${OUTPUT}" | grep 'Successfully un-mapped')
       if [ $? -ne 0 ]; then
-        echo "${OUTPUT}"; echo
-        echo "WARNING: Volume unmap to this SDC was not successful. You may need to do the following manually on the primary MDM:"
-        echo "scli --unmap_volume_from_sdc --volume_id ${VOLUME_ID} --sdc_ip ${MYIP} --i_am_sure"; exit
+        if [ ${VERBOSE} -eq 1 ]; then echo -e "${OUTPUT}\n"; fi
+        (>&2 echo "WARNING: Volume unmap to this SDC was not successful. You may need to do the following manually on the primary MDM:")
+        (>&2 echo "scli --unmap_volume_from_sdc --volume_id ${VOLUME_ID} --sdc_ip ${MYIP} --i_am_sure"); exit 2
       fi
     else
-      echo "${OUTPUT}"; echo; echo "ERROR: Aborting."; exit     
+      (>&2 echo -e "\n${OUTPUT}\nERROR: Failed to successfull map volume to this SDC."); exit 1
     fi
   else
-    echo "${OUTPUT}"; echo; echo "Unable to find unmapped volume ${VOLUME_ID}, aborting."; exit
+    (>&2 echo -e "\n${OUTPUT}\nERROR: Unable to find unmapped volume ${VOLUME_ID}."); exit 1
   fi
+else
+  (>&2 echo "ERROR: Could not determine the primary ScaleIO MDM server. Aborting."); exit 1
 fi
diff --git a/restore_snapshot b/restore_snapshot
--- a/restore_snapshot
+++ b/restore_snapshot
@@ -1,33 +1,69 @@
 #!/bin/bash
 
-SCALEIO_SERVERS="scale1.example.com scale2.example.com scale3.example.com"
+SCALEIO_SERVERS="scaleio1.example.com scaleio2.example.com scaleio3.example.com"
 SCALEIO_PW="SCALEIO_ADMIN_PASSWORD"
-PROTECTION_DOMAIN_NAME=domain1
-STORAGE_POOL_NAME=pool1
+PROTECTION_DOMAIN_NAME=default
+STORAGE_POOL_NAME=default
 TARGET_DEVICE=/dev/scinia
-MYIP=192.168.33.1
-PASSWORD_FILE=/etc/scaleio-backup-password.txt
+MYIP=224.36.61.210
+PASSWORD_FILE=/etc/backup-passwords.txt
 
-display_usage() {
-        echo "This script will create a new ScaleIO volume of the specified size and restore an encrypted gzip volume dump into it."
-        echo "Usage: restore_snapshot (new_volume_name) (size_in_gb) (encrypted_gz_filename)"
-	echo
-        echo "Example: restore_snapshot testvol2 16 /volumedump/596fbe910000001b.gz"
-        echo
+show_help() {
+        echo -e "\nThis script will create a new ScaleIO volume of the specified size, temporarily attach it to ${TARGET_DEVICE} on this host, and restore an encrypted gzip volume dump into it."
+        echo -e "\nUsage: restore_snapshot [OPTIONS] (-n new_volume_name) (-s size_in_gb) (-f encrypted_gz_filename)"
+        echo -e "\nExample: restore_snapshot -n testvol2 -s 16 -f /volumedump/596fbe910000001b.gz\n"
+        echo "OPTIONS:"
+        echo " -h, -?   help"
+        echo " -f       filepath of encrypted gzip file"
+        echo " -n       name of the new scaleIO volume to create"
+        echo " -s       size of the new volume to create (should match the original dumped volume size)"
+        echo -e " -v       increase verbosity\n"
         exit 1
 }
 
-if [  $# -ne 3 ]
+OPTIND=1
+VOLUME_NAME=
+SIZE=
+FILEPATH=
+VERBOSE=0
+
+while getopts "f:h?n:s:v" opt; do
+    case "$opt" in
+    f)  FILEPATH=$OPTARG
+        ;;
+    h|\?)
+        show_help
+        exit 0
+        ;;
+    n)  VOLUME_NAME=$OPTARG
+        ;;
+    s)  SIZE=$OPTARG
+        ;;
+    v)  VERBOSE=1
+        ;;
+    esac
+done
+
+shift $((OPTIND-1))
+
+if [ "${VOLUME_NAME}" == "" ]
 then
-        display_usage
+        show_help
         exit 1
 fi
-VOLUME_NAME=$1
-SIZE=$2
-FILENAME=$3
+if [ "${SIZE}" == "" ]
+then
+        show_help
+        exit 1
+fi
+if [ "${FILEPATH}" == "" ]
+then
+        show_help
+        exit 1
+fi
 
-if [ ! -f ${FILENAME} ]; then
-  echo; echo "ERROR: Unable to find ${FILENAME}. Aborting."; exit
+if [ ! -f ${FILEPATH} ]; then
+  echo -e "\nERROR: Unable to find ${FILEPATH}. Aborting."; exit 1
 fi
 
 #Find out which server is our current primary MDM
@@ -44,39 +80,43 @@ for SERVER in ${SCALEIO_SERVERS}; do
 done
 
 if [ "${PRIMARY_SERVER}" != "" ]; then
+  if [ ${VERBOSE} -eq 1 ]; then echo -e "Found primary ScaleIO MDM ${PRIMARY_SERVER}\n"; fi
   OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --query_volume --volume_name ${VOLUME_NAME} 2>&1")
   #Error: MDM failed command.  Status: Could not find the volume
   WORKED=$(echo "${OUTPUT}" | grep 'Could not find the volume')
   if [ $? -eq 0 ]; then
     OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --add_volume --protection_domain_name ${PROTECTION_DOMAIN_NAME} --storage_pool_name ${STORAGE_POOL_NAME} --size_gb ${SIZE} --volume_name ${VOLUME_NAME} --thin_provisioned")
     #Successfully created volume of size 16 GB. Object ID 597033bf0000003c
+    if [ ${VERBOSE} -eq 1 ]; then echo -e "${OUTPUT}\n"; fi
     WORKED=$(echo "${OUTPUT}" | grep 'Successfully created volume')
     if [ $? -eq 0 ]; then
       VOLUME_ID=$(echo "${OUTPUT}" | awk '/Object ID/ {print $NF}')
       WORKED=$(echo "${VOLUME_ID}" | egrep '[0-9a-f]{16}')
       if [ $? -eq 0 ]; then
         OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --map_volume_to_sdc --volume_id ${VOLUME_ID} --sdc_ip ${MYIP}")
+        if [ ${VERBOSE} -eq 1 ]; then echo -e "${OUTPUT}\n"; fi
         #Successfully mapped volume with ID 597033bd0000001f to SDC 224.36.61.124
         WORKED=$(echo "${OUTPUT}" | grep "Successfully mapped")
         if [ $? -eq 0 ]; then
           sleep 5
-          time openssl enc -d -aes-256-cbc -pass file:${PASSWORD_FILE} -in ${FILENAME} | gunzip -dc | dd bs=1048576 of=${TARGET_DEVICE}
+          time openssl enc -d -aes-256-cbc -pass file:${PASSWORD_FILE} -in ${FILEPATH} | gunzip -dc | dd bs=1048576 of=${TARGET_DEVICE}
           OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --unmap_volume_from_sdc --volume_id ${VOLUME_ID} --sdc_ip ${MYIP} --i_am_sure")
           #Successfully un-mapped volume with ID 597033bd0000001f from SDC 224.36.61.124
+          if [ ${VERBOSE} -eq 1 ]; then echo -e "${OUTPUT}\n"; fi
           WORKED=$(echo "${OUTPUT}" | grep "Successfully un-mapped")
           if [ $? -ne 0 ]; then
             echo "${OUTPUT}"; echo
             echo "WARNING: Volume unmap from SDC ${MY_IP} was not successful. You may need to do the following manually on the primary MDM:"
-            echo "scli --unmap_volume_from_sdc --volume_id ${VOLUME_ID} --sdc_ip ${MYIP} --i_am_sure"; exit
+            echo "scli --unmap_volume_from_sdc --volume_id ${VOLUME_ID} --sdc_ip ${MYIP} --i_am_sure"; exit 1
           fi
         else
-          echo "${OUTPUT}"; echo; echo "ERROR: Did not successfully map volume ID ${VOLUME_ID} to SDC ${MYIP}."; exit
+          echo -e "${OUTPUT}\nERROR: Did not successfully map volume ID ${VOLUME_ID} to SDC ${MYIP}."; exit 1
         fi
       else
-        echo "${OUTPUT}"; echo; echo "ERROR: Could not find new volume ID."; exit
+        echo -e "\n${OUTPUT}\nERROR: Could not find new volume ID."; exit 1
       fi
     else
-      echo "${OUTPUT}"; echo; echo "ERROR: Failed to create volume ${VOLUME_NAME} with size ${SIZE}."; exit
+      echo -e "\n${OUTPUT}\nERROR: Failed to create volume ${VOLUME_NAME} with size ${SIZE}."; exit 1
     fi 
   else
     echo "${OUTPUT}"; echo; echo "ERROR: Please check that ${VOLUME_NAME} doesn't already exist."; exit
diff --git a/snapshot_volume b/snapshot_volume
--- a/snapshot_volume
+++ b/snapshot_volume
@@ -1,20 +1,46 @@
 #!/bin/bash
 
-SCALEIO_SERVERS="scale1.example.com scale2.example.com scale3.example.com"
+SCALEIO_SERVERS="scaleio1.example.com scaleio2.example.com scaleio3.example.com"
 SCALEIO_PW="SCALEIO_ADMIN_PASSWORD"
 
-display_usage() { 
-	echo "This script will snapshot a given volume ID, first deleting the oldest snapshot if 31 snapshots already exist."
-	echo -e "\nUsage:\nsnapshot_volume (volume_name) \n" 
+show_help() { 
+	echo -e "\nThis script will snapshot a given volume ID, first deleting the oldest snapshot if 31 snapshots already exist."
+	echo -e "\nUsage:  snapshot_volume [OPTIONS] (-n volume_name) \n" 
+	echo "OPTIONS:" 
+	echo " -h, -?   help" 
+	echo " -i       display only then new shapshot_ID upon success" 
+	echo " -n       ScaleIO volume_name to snapshot" 
+	echo -e " -v       increase verbosity\n" 
         exit 1
 } 
 
-if [  $# -ne 1 ] 
+OPTIND=1
+VOLUME_NAME=
+ID_ONLY=0
+VERBOSE=0
+
+while getopts "h?in:v" opt; do
+    case "$opt" in
+    h|\?)
+        show_help
+        exit 0
+        ;;
+    i)  ID_ONLY=1
+        ;;
+    n)  VOLUME_NAME=$OPTARG
+        ;;
+    v)  VERBOSE=1
+        ;;
+    esac
+done
+
+shift $((OPTIND-1))
+
+if [ "${VOLUME_NAME}" == "" ] 
 then 
-	display_usage
+	show_help
 	exit 1
 fi 
-VOLUME_NAME=$1
 
 #Find out which server is our current primary MDM
 PRIMARY_SERVER=
@@ -30,6 +56,7 @@ for SERVER in ${SCALEIO_SERVERS}; do
 done
 
 if [ "${PRIMARY_SERVER}" != "" ]; then
+  if [ ${VERBOSE} -eq 1 ]; then echo -e "Found primary ScaleIO MDM ${PRIMARY_SERVER}\n"; fi
   OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --query_all_volume") 
   WORKED=$(echo "${OUTPUT}" | grep "Name: ${VOLUME_NAME}") 
   if [ $? -eq 0 ]; then
@@ -38,12 +65,19 @@ if [ "${PRIMARY_SERVER}" != "" ]; then
     if [ "${SNAP_COUNT}" == "31" ]; then
       OLDEST_SNAP=$(echo "${SNAPSHOTS}" | awk '{print $3}' | sort | head -1)
       OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --remove_volume --volume_id ${OLDEST_SNAP} --i_am_sure")
+      if [ ${VERBOSE} -eq 1 ]; then echo -e "Removing oldest snapshot as 31 currently exist.\n${OUTPUT}\n"; fi
       sleep 3
-      ssh ${PRIMARY_SERVER} "scli --snapshot_volume --volume_name ${VOLUME_NAME}"
+      OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --snapshot_volume --volume_name ${VOLUME_NAME}")
+      if [ ${ID_ONLY} -eq 0 ]; then echo -e "${OUTPUT}\n"; fi
+      if [ ${ID_ONLY} -eq 1 ]; then echo "${OUTPUT}" | awk '/=>/ {print $NF}'; fi
     else
-      ssh ${PRIMARY_SERVER} "scli --snapshot_volume --volume_name ${VOLUME_NAME}"
+      OUTPUT=$(ssh ${PRIMARY_SERVER} "scli --snapshot_volume --volume_name ${VOLUME_NAME}")
+      if [ ${ID_ONLY} -eq 0 ]; then echo -e "${OUTPUT}\n"; fi
+      if [ ${ID_ONLY} -eq 1 ]; then echo "${OUTPUT}" | awk '/=>/ {print $NF}'; fi
     fi
   else
-    echo "${OUTPUT}"; echo; echo "Volume ${VOLUME_NAME} not found."; exit
+    (>&2 echo -e "\n${OUTPUT}\nERROR: Volume name ${VOLUME_NAME} not found."); exit 1
   fi
+else
+  (>&2 echo "ERROR: Could not determine the primary ScaleIO MDM server. Aborting."); exit 1
 fi
