added exit code to an error condition

diff --git a/restore_snapshot b/restore_snapshot
--- a/restore_snapshot
+++ b/restore_snapshot
@@ -124,6 +124,6 @@ if [ "${PRIMARY_SERVER}" != "" ]; then
       echo -e "\n${OUTPUT}\nERROR: Failed to create volume ${VOLUME_NAME} with size ${SIZE}."; exit 1
     fi 
   else
-    echo "${OUTPUT}"; echo; echo "ERROR: Please check that ${VOLUME_NAME} doesn't already exist."; exit
+    echo "${OUTPUT}"; echo; echo "ERROR: Please check that ${VOLUME_NAME} doesn't already exist."; exit 1 1
   fi
 fi
